CREATE TABLE Products (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ProductName NVARCHAR(255) NOT NULL,
    Price DECIMAL(18, 4) NOT NULL,
    Source NVARCHAR(255) NOT NULL,
    RetrievedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
